
context("SequenceData")
test_that("SequenceData:",{
  # SequenceData using CoverageSequenceData as test case
  annotation <- system.file("extdata","example1.gff3",package = "RNAmodR.Data")
  sequences <- system.file("extdata","example1.fasta",package = "RNAmodR.Data")
  files <- c(control = system.file("extdata","example_wt_1.bam",
                                   package = "RNAmodR.Data"),
             treated = system.file("extdata","example_wt_2.bam",
                                   package = "RNAmodR.Data"))
  csd <- CoverageSequenceData(files, annotation = annotation,
                              sequences = sequences)
  expect_s4_class(csd,"CoverageSequenceData")
  expect_named(csd,c("1","2"))
  expect_s4_class(colnames(csd),"CharacterList")
  expect_length(colnames(csd),2)
  expect_equal(lengths(colnames(csd)),c(2,2))
  expect_equal(colnames(csd)[[1]],colnames(csd)[[2]])
  expect_equal(colnames(csd)[[1]],c("coverage.control.1","coverage.treated.1"))
  actual <- aggregate(csd)
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(4,4))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","means.treated",
                                       "sds.control","sds.treated"))
  expect_s4_class(seqinfo(csd),"Seqinfo")
  expect_equal(length(seqinfo(csd)),11)
  actual <- aggregate(csd, condition = "Control")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","sds.control"))
  expect_s4_class(seqinfo(csd),"Seqinfo")
  expect_equal(length(seqinfo(csd)),11)
  actual <- aggregate(csd, condition = "Treated")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.treated","sds.treated"))
  expect_s4_class(seqinfo(csd),"Seqinfo")
  expect_equal(length(seqinfo(csd)),11)
})
