
context("EndSequenceData")
test_that("EndSequenceData:",{
  # SequenceData using CoverageSequenceData as test case
  library(RNAmodR.Data)
  library(rtracklayer)
  annotation <- GFF3File(RNAmodR.Data.example.man.gff3())
  sequences <- RNAmodR.Data.example.man.fasta()
  files <- c(control = RNAmodR.Data.example.wt.1(),
             treated = RNAmodR.Data.example.wt.2())
  #
  e5sd <- End5SequenceData(files, annotation = annotation,
                              sequences = sequences)
  expect_false(any(lengths(rownames(e5sd)) == 0L))
  expect_s4_class(e5sd,"End5SequenceData")
  expect_named(e5sd,c("1","2"))
  expect_s4_class(colnames(e5sd),"CharacterList")
  expect_length(colnames(e5sd),2)
  expect_equal(lengths(colnames(e5sd)),c(2,2))
  expect_equal(colnames(e5sd)[[1]],colnames(e5sd)[[2]])
  expect_equal(colnames(e5sd)[[1]],c("end5.control.1","end5.treated.1"))
  actual <- aggregate(e5sd)
  expect_false(any(lengths(rownames(actual)) == 0L))
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(4,4))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","means.treated",
                                       "sds.control","sds.treated"))
  expect_s4_class(seqinfo(e5sd),"Seqinfo")
  expect_equal(length(seqinfo(e5sd)),11)
  actual <- aggregate(e5sd, condition = "Control")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","sds.control"))
  expect_s4_class(seqinfo(e5sd),"Seqinfo")
  expect_equal(length(seqinfo(e5sd)),11)
  actual <- aggregate(e5sd, condition = "Treated")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.treated","sds.treated"))
  expect_s4_class(seqinfo(e5sd),"Seqinfo")
  expect_equal(length(seqinfo(e5sd)),11)
  # General accessors
  expect_type(names(e5sd),"character")
  expect_s4_class(seqinfo(e5sd),"Seqinfo")
  expect_s4_class(sequences(e5sd),"RNAStringSet")
  expect_s4_class(ranges(e5sd),"GRangesList")
  expect_true(is.factor(conditions(e5sd)))
  expect_equal(conditions(e5sd),factor(c("control","treated")))
  expect_true(is.factor(replicates(e5sd)))
  expect_equal(replicates(e5sd),factor(c(1,1)))
  #
  e3sd <- End3SequenceData(files, annotation = annotation,
                          sequences = sequences)
  expect_false(any(lengths(rownames(e3sd)) == 0L))
  expect_s4_class(e3sd,"End3SequenceData")
  expect_named(e3sd,c("1","2"))
  expect_s4_class(colnames(e3sd),"CharacterList")
  expect_length(colnames(e3sd),2)
  expect_equal(lengths(colnames(e3sd)),c(2,2))
  expect_equal(colnames(e3sd)[[1]],colnames(e3sd)[[2]])
  expect_equal(colnames(e3sd)[[1]],c("end3.control.1","end3.treated.1"))
  actual <- aggregate(e3sd)
  expect_false(any(lengths(rownames(actual)) == 0L))
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(4,4))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","means.treated",
                                       "sds.control","sds.treated"))
  expect_s4_class(seqinfo(e3sd),"Seqinfo")
  expect_equal(length(seqinfo(e3sd)),11)
  actual <- aggregate(e3sd, condition = "Control")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","sds.control"))
  expect_s4_class(seqinfo(e3sd),"Seqinfo")
  expect_equal(length(seqinfo(e3sd)),11)
  actual <- aggregate(e3sd, condition = "Treated")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.treated","sds.treated"))
  expect_s4_class(seqinfo(e3sd),"Seqinfo")
  expect_equal(length(seqinfo(e3sd)),11)
  #
  esd <- EndSequenceData(files, annotation = annotation,
                          sequences = sequences)
  expect_false(any(lengths(rownames(esd)) == 0L))
  expect_s4_class(esd,"EndSequenceData")
  expect_named(esd,c("1","2"))
  expect_s4_class(colnames(esd),"CharacterList")
  expect_length(colnames(esd),2)
  expect_equal(lengths(colnames(esd)),c(2,2))
  expect_equal(colnames(esd)[[1]],colnames(esd)[[2]])
  expect_equal(colnames(esd)[[1]],c("end.control.1","end.treated.1"))
  actual <- aggregate(esd)
  expect_false(any(lengths(rownames(actual)) == 0L))
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(4,4))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","means.treated",
                                       "sds.control","sds.treated"))
  expect_s4_class(seqinfo(esd),"Seqinfo")
  expect_equal(length(seqinfo(esd)),11)
  actual <- aggregate(esd, condition = "Control")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.control","sds.control"))
  expect_s4_class(seqinfo(esd),"Seqinfo")
  expect_equal(length(seqinfo(esd)),11)
  actual <- aggregate(esd, condition = "Treated")
  expect_s4_class(actual,"CompressedSplitDataFrameList")
  expect_s4_class(actual,"SplitDataFrameList")
  expect_equal(length(actual),2)
  expect_length(colnames(actual),2)
  expect_equal(lengths(colnames(actual)),c(2,2))
  expect_equal(colnames(actual)[[1]],colnames(actual)[[2]])
  expect_equal(colnames(actual)[[1]],c("means.treated","sds.treated"))
  expect_s4_class(seqinfo(esd),"Seqinfo")
  expect_equal(length(seqinfo(esd)),11)
})
