#' @include RNAmodR.R
NULL

# general help functions -------------------------------------------------------

# returns subset list based on logical vector generated by supplied function
# if FUN is missing is.null is used
# result of FUN determines removal by returning TRUE
.clean_output <- function(data, 
                          FUN){
  assertive::assert_is_list(data)
  if(missing(FUN)) FUN = is.null
  data[!vapply(data, FUN, logical(1))]
}

# derivate of .clean_output
# works on a list of lists
.clean_output2 <- function(data, 
                           FUN){
  assertive::assert_is_list(data)
  if(missing(FUN)) FUN = is.null
  res <- lapply(data, function(x){
    x <- .clean_output(x, FUN)
    if(length(x) == 0) return(NULL)
    x
  })
  names(res) <- names(data)
  res[!vapply(res, is.null, logical(1))]
}

# fix for arrangeGrob opening drawing device, where it should't
.arrangeGrob.fixed <- function(...){
  grDevices::pdf(file = NULL)
  grid <- do.call(gridExtra::arrangeGrob, list(...))
  grDevices::dev.off()
  return(grid)
}

#input type checks
.checkValueValidity <- function(value,
                                checkValues,
                                fatal = TRUE,
                                .xvalue = assertive::get_name_in_parent(value)){
  check <- value %in% checkValues
  if(!check && fatal){
    stop("'",.xvalue,
         "' must be one of the following values: '",
         paste(checkValues, collapse = "', '"),
         "'.",
         call. = FALSE)
  }
  return(invisible(check))
}
.check_sample_conditions <- function(conditions){
  .checkValueValidity(conditions,
                      RNAMODR_SAMPLE_TYPES)
}
.check_for_mod_classes <- function(modifications){
  modClasses <- .load_mod_classes(modifications)
  .checkValueValidity(conditions,
                      names(modClasses))
}

# check list members for class name
.checkListForClass <- function(x,
                               classname,
                               checkFunction = FALSE,
                               .xname = assertive::get_name_in_parent(x)){
  check <- vapply(x,
                  function(x){
                    class(x) == classname
                  },
                  logical(1))
  if(!all(check)){
    stop("'",.xname,"' does contain elements, which are not of class '",
         classname,
         "'.",
         call. = FALSE)
  }
  if(is.function(checkFunction)){
    check <- vapply(x,
                    checkFunction,
                    logical(1))
    if(!all(check)){
      stop("'",.xname,"' does contain elements, which do not contain ",
           "the required data.",
           call. = FALSE)
    }
  }
  return(invisible(TRUE))
}


# debug helper -----------------------------------------------------------------

.print_location_info <- function(location, locs){
  message("location: ",location," //locs: ",paste(locs,collapse = ","))
}
.print_transcript_info <- function(ID, iterationN){
  message(ID, " - iteration: ",iterationN)
}
