#' @include RNAmodR.R
NULL

# general help functions -------------------------------------------------------

# returns subset list based on logical vector generated by supplied function
# if FUN is missing is.null is used
# result of FUN determines removal by returning TRUE
.clean_output <- function(data, 
                          FUN){
  assertive::assert_is_list(data)
  if(missing(FUN)) FUN = is.null
  data[!vapply(data, FUN, logical(1))]
}

# derivate of .clean_output
# works on a list of lists
.clean_output2 <- function(data, 
                           FUN){
  assertive::assert_is_list(data)
  if(missing(FUN)) FUN = is.null
  res <- lapply(data, function(x){
    x <- .clean_output(x, FUN)
    if(length(x) == 0) return(NULL)
    x
  })
  names(res) <- names(data)
  res[!vapply(res, is.null, logical(1))]
}


# debug helper -----------------------------------------------------------------

.print_location_info <- function(location, locs){
  message("location: ",location," //locs: ",paste(locs,collapse = ","))
}
.print_transcript_info <- function(ID, iterationN){
  message(ID, " - iteration: ",iterationN)
}
